import type { Metadata } from "next"
import "./globals.css"
import ThemeWrapper from "@/components/ThemeWrapper/ThemeWrapper"
import { AuthProvider } from "@/contexts/AuthContext"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="he">
      <body>
        <ThemeWrapper>
          <AuthProvider>{children}</AuthProvider>
        </ThemeWrapper>
      </body>
    </html>
  )
}
